name: grubbyy_admin

description: A preordering app admin panel for managing orders and payments.

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  cloud_firestore: ^4.10.0
  firebase_auth: ^4.7.0
  fl_chart: ^0.40.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
